### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by amansinghaljpr** [goroshii/SIM800L_Firebase#1]
Hey there , your library does not have any basic arduino example code which made it difficult for the user to write a code . Can you please provide a example code which is easy to understand and can be used to send data over firebase database using sim800L

**Comment by Vish1998** [comment]
> Hey there , your library does not have any basic arduino example code which made it difficult for the user to write a code . Can you please provide a example code which is easy to understand and can be used to send data over firebase database using sim800L

hey, did you get any code to connect to firebase using SIM800L

**Comment by dmquirozc** [comment]
Hi guys, sorry for the problems. I have answered an email with examples, but here in the last commit I have added an examples.
This examples was made on 2018 so if you have any  questions  i'm here for you.
